name: taskmaster

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8081:8081"

  client:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - server
