name: taskmaster

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8081:8081"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
