[program.one]
command = "ping localhost"
stopsignal = "TERM"
stdout_logfile = "one.log"
# autostart = false

[program.two]
command = "sleep 3"
stopsignal = "INT"
stdout_logfile = "two.log"
# autostart = false
startsecs = 5
startretries = 10

[program.three]
# autostart = false
command = "ping 0.0.0.0"
stdout_logfile = "three.log"
